// Code generated by protoc-gen-go. DO NOT EDIT.
// source: openconfig_rib.proto

package mt_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EntriesEntry struct {
	EntryKey             string   `protobuf:"bytes,1,opt,name=entryKey,proto3" json:"entryKey,omitempty"`
	EntryDetail          string   `protobuf:"bytes,2,opt,name=entryDetail,proto3" json:"entryDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntriesEntry) Reset()         { *m = EntriesEntry{} }
func (m *EntriesEntry) String() string { return proto.CompactTextString(m) }
func (*EntriesEntry) ProtoMessage()    {}
func (*EntriesEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_40524236ffe6db69, []int{0}
}

func (m *EntriesEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntriesEntry.Unmarshal(m, b)
}
func (m *EntriesEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntriesEntry.Marshal(b, m, deterministic)
}
func (m *EntriesEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntriesEntry.Merge(m, src)
}
func (m *EntriesEntry) XXX_Size() int {
	return xxx_messageInfo_EntriesEntry.Size(m)
}
func (m *EntriesEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_EntriesEntry.DiscardUnknown(m)
}

var xxx_messageInfo_EntriesEntry proto.InternalMessageInfo

func (m *EntriesEntry) GetEntryKey() string {
	if m != nil {
		return m.EntryKey
	}
	return ""
}

func (m *EntriesEntry) GetEntryDetail() string {
	if m != nil {
		return m.EntryDetail
	}
	return ""
}

type RibTableEntries struct {
	Entry                []*EntriesEntry `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RibTableEntries) Reset()         { *m = RibTableEntries{} }
func (m *RibTableEntries) String() string { return proto.CompactTextString(m) }
func (*RibTableEntries) ProtoMessage()    {}
func (*RibTableEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_40524236ffe6db69, []int{1}
}

func (m *RibTableEntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RibTableEntries.Unmarshal(m, b)
}
func (m *RibTableEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RibTableEntries.Marshal(b, m, deterministic)
}
func (m *RibTableEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RibTableEntries.Merge(m, src)
}
func (m *RibTableEntries) XXX_Size() int {
	return xxx_messageInfo_RibTableEntries.Size(m)
}
func (m *RibTableEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_RibTableEntries.DiscardUnknown(m)
}

var xxx_messageInfo_RibTableEntries proto.InternalMessageInfo

func (m *RibTableEntries) GetEntry() []*EntriesEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func init() {
	proto.RegisterType((*EntriesEntry)(nil), "mt.proto.EntriesEntry")
	proto.RegisterType((*RibTableEntries)(nil), "mt.proto.RibTableEntries")
}

func init() { proto.RegisterFile("openconfig_rib.proto", fileDescriptor_40524236ffe6db69) }

var fileDescriptor_40524236ffe6db69 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc9, 0x2f, 0x48, 0xcd,
	0x4b, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0x8f, 0x2f, 0xca, 0x4c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0xc8, 0x2d, 0x81, 0xb0, 0x94, 0x7c, 0xb8, 0x78, 0x5c, 0xf3, 0x4a, 0x8a, 0x32, 0x53,
	0x8b, 0x41, 0x54, 0xa5, 0x90, 0x14, 0x17, 0x47, 0x2a, 0x88, 0xe1, 0x9d, 0x5a, 0x29, 0xc1, 0xa8,
	0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x0b, 0x29, 0x70, 0x71, 0x83, 0xd9, 0x2e, 0xa9, 0x25, 0x89,
	0x99, 0x39, 0x12, 0x4c, 0x60, 0x69, 0x64, 0x21, 0x25, 0x7b, 0x2e, 0xfe, 0xa0, 0xcc, 0xa4, 0x90,
	0xc4, 0xa4, 0x9c, 0x54, 0xa8, 0xa9, 0x42, 0x3a, 0x5c, 0xac, 0x60, 0x15, 0x12, 0x8c, 0x0a, 0xcc,
	0x1a, 0xdc, 0x46, 0x62, 0x7a, 0x30, 0xab, 0xf5, 0x90, 0xed, 0x0d, 0x82, 0x28, 0x4a, 0x62, 0x03,
	0x4b, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x61, 0xbd, 0x1f, 0xd8, 0xb7, 0x00, 0x00, 0x00,
}
