// Code generated by protoc-gen-go. DO NOT EDIT.
// source: openconfig_rib.proto

package gnmi_sonic

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EntriesEntry struct {
	Destination          string   `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Netmask              string   `protobuf:"bytes,2,opt,name=netmask,proto3" json:"netmask,omitempty"`
	NexthopMac           string   `protobuf:"bytes,3,opt,name=nexthop_mac,json=nexthopMac,proto3" json:"nexthop_mac,omitempty"`
	Interface            string   `protobuf:"bytes,4,opt,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntriesEntry) Reset()         { *m = EntriesEntry{} }
func (m *EntriesEntry) String() string { return proto.CompactTextString(m) }
func (*EntriesEntry) ProtoMessage()    {}
func (*EntriesEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_40524236ffe6db69, []int{0}
}

func (m *EntriesEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntriesEntry.Unmarshal(m, b)
}
func (m *EntriesEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntriesEntry.Marshal(b, m, deterministic)
}
func (m *EntriesEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntriesEntry.Merge(m, src)
}
func (m *EntriesEntry) XXX_Size() int {
	return xxx_messageInfo_EntriesEntry.Size(m)
}
func (m *EntriesEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_EntriesEntry.DiscardUnknown(m)
}

var xxx_messageInfo_EntriesEntry proto.InternalMessageInfo

func (m *EntriesEntry) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *EntriesEntry) GetNetmask() string {
	if m != nil {
		return m.Netmask
	}
	return ""
}

func (m *EntriesEntry) GetNexthopMac() string {
	if m != nil {
		return m.NexthopMac
	}
	return ""
}

func (m *EntriesEntry) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

type RibTableEntries struct {
	Entry                []*EntriesEntry `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RibTableEntries) Reset()         { *m = RibTableEntries{} }
func (m *RibTableEntries) String() string { return proto.CompactTextString(m) }
func (*RibTableEntries) ProtoMessage()    {}
func (*RibTableEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_40524236ffe6db69, []int{1}
}

func (m *RibTableEntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RibTableEntries.Unmarshal(m, b)
}
func (m *RibTableEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RibTableEntries.Marshal(b, m, deterministic)
}
func (m *RibTableEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RibTableEntries.Merge(m, src)
}
func (m *RibTableEntries) XXX_Size() int {
	return xxx_messageInfo_RibTableEntries.Size(m)
}
func (m *RibTableEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_RibTableEntries.DiscardUnknown(m)
}

var xxx_messageInfo_RibTableEntries proto.InternalMessageInfo

func (m *RibTableEntries) GetEntry() []*EntriesEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type RibTable struct {
	Entries              *RibTableEntries `protobuf:"bytes,1,opt,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RibTable) Reset()         { *m = RibTable{} }
func (m *RibTable) String() string { return proto.CompactTextString(m) }
func (*RibTable) ProtoMessage()    {}
func (*RibTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_40524236ffe6db69, []int{2}
}

func (m *RibTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RibTable.Unmarshal(m, b)
}
func (m *RibTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RibTable.Marshal(b, m, deterministic)
}
func (m *RibTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RibTable.Merge(m, src)
}
func (m *RibTable) XXX_Size() int {
	return xxx_messageInfo_RibTable.Size(m)
}
func (m *RibTable) XXX_DiscardUnknown() {
	xxx_messageInfo_RibTable.DiscardUnknown(m)
}

var xxx_messageInfo_RibTable proto.InternalMessageInfo

func (m *RibTable) GetEntries() *RibTableEntries {
	if m != nil {
		return m.Entries
	}
	return nil
}

type Rib struct {
	RibTable             *RibTable `protobuf:"bytes,1,opt,name=rib_table,json=ribTable,proto3" json:"rib_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Rib) Reset()         { *m = Rib{} }
func (m *Rib) String() string { return proto.CompactTextString(m) }
func (*Rib) ProtoMessage()    {}
func (*Rib) Descriptor() ([]byte, []int) {
	return fileDescriptor_40524236ffe6db69, []int{3}
}

func (m *Rib) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rib.Unmarshal(m, b)
}
func (m *Rib) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rib.Marshal(b, m, deterministic)
}
func (m *Rib) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rib.Merge(m, src)
}
func (m *Rib) XXX_Size() int {
	return xxx_messageInfo_Rib.Size(m)
}
func (m *Rib) XXX_DiscardUnknown() {
	xxx_messageInfo_Rib.DiscardUnknown(m)
}

var xxx_messageInfo_Rib proto.InternalMessageInfo

func (m *Rib) GetRibTable() *RibTable {
	if m != nil {
		return m.RibTable
	}
	return nil
}

func init() {
	proto.RegisterType((*EntriesEntry)(nil), "sonic.rib.EntriesEntry")
	proto.RegisterType((*RibTableEntries)(nil), "sonic.rib.RibTableEntries")
	proto.RegisterType((*RibTable)(nil), "sonic.rib.RibTable")
	proto.RegisterType((*Rib)(nil), "sonic.rib.Rib")
}

func init() { proto.RegisterFile("openconfig_rib.proto", fileDescriptor_40524236ffe6db69) }

var fileDescriptor_40524236ffe6db69 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc7, 0xa9, 0x55, 0x77, 0x3b, 0x15, 0x84, 0x28, 0x18, 0x44, 0xb0, 0xf4, 0xb4, 0x17, 0x8b,
	0xac, 0x82, 0xd7, 0xbd, 0x78, 0xf4, 0x12, 0xbc, 0x97, 0x24, 0xce, 0xea, 0xa0, 0x3b, 0x29, 0x69,
	0x0e, 0xfa, 0x08, 0xbe, 0xb5, 0x34, 0x4d, 0xb5, 0xc8, 0x9e, 0x92, 0xfc, 0x3f, 0x92, 0x5f, 0x06,
	0xce, 0x5d, 0x87, 0x6c, 0x1d, 0x6f, 0xe9, 0xb5, 0xf5, 0x64, 0x9a, 0xce, 0xbb, 0xe0, 0x44, 0xd1,
	0x3b, 0x26, 0xdb, 0x78, 0x32, 0xf5, 0x77, 0x06, 0x27, 0x8f, 0x1c, 0x3c, 0x61, 0x3f, 0x2c, 0x5f,
	0xa2, 0x82, 0xf2, 0x05, 0xfb, 0x40, 0xac, 0x03, 0x39, 0x96, 0x59, 0x95, 0xad, 0x0a, 0x35, 0x97,
	0x84, 0x84, 0x05, 0x63, 0xd8, 0xe9, 0xfe, 0x5d, 0x1e, 0x44, 0x77, 0x3a, 0x8a, 0x6b, 0x28, 0x19,
	0x3f, 0xc3, 0x9b, 0xeb, 0xda, 0x9d, 0xb6, 0x32, 0x8f, 0x2e, 0x24, 0xe9, 0x49, 0x5b, 0x71, 0x05,
	0x05, 0x71, 0x40, 0xbf, 0xd5, 0x16, 0xe5, 0x61, 0xb4, 0xff, 0x84, 0x7a, 0x03, 0xa7, 0x8a, 0xcc,
	0xb3, 0x36, 0x1f, 0x98, 0x90, 0xc4, 0x0d, 0x1c, 0xe1, 0x80, 0x25, 0xb3, 0x2a, 0x5f, 0x95, 0xeb,
	0x8b, 0xe6, 0x97, 0xbc, 0x99, 0x53, 0xab, 0x31, 0x55, 0x6f, 0x60, 0x39, 0xdd, 0x20, 0xee, 0x61,
	0x81, 0x63, 0x24, 0x7e, 0xa2, 0x5c, 0x5f, 0xce, 0xca, 0xff, 0xde, 0x51, 0x53, 0xb4, 0x7e, 0x80,
	0x5c, 0x91, 0x11, 0xb7, 0x50, 0x78, 0x32, 0x6d, 0x18, 0x32, 0xa9, 0x7e, 0xb6, 0xa7, 0xae, 0x96,
	0x3e, 0xed, 0xcc, 0x71, 0x1c, 0xed, 0xdd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x2f, 0x68,
	0xb8, 0x72, 0x01, 0x00, 0x00,
}
